//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetSmartArcGISPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetSmartArcGISPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FocusMode16 {
            get {
                object obj = ResourceManager.GetObject("FocusMode16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no pdf viewer available on your system, please first install a pdf viewer.
        /// </summary>
        internal static string Help_pdf_viewer_is_not_installed_on_your_system_ {
            get {
                return ResourceManager.GetString("Help_pdf_viewer_is_not_installed_on_your_system_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        internal static string Login_CreateAes_Password_must_be_at_least_8_characters_ {
            get {
                return ResourceManager.GetString("Login_CreateAes_Password_must_be_at_least_8_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt must be at least 8 bytes..
        /// </summary>
        internal static string Login_CreateAes_Salt_must_be_at_least_8_bytes_ {
            get {
                return ResourceManager.GetString("Login_CreateAes_Salt_must_be_at_least_8_bytes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streetSmart ArcGISPro Addin Error..
        /// </summary>
        internal static string streetSmart_ArcGISPro_Error_ {
            get {
                return ResourceManager.GetString("streetSmart_ArcGISPro_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the new Cyclorama viewer. Max number of Cyclorama viewers reached..
        /// </summary>
        internal static string streetSmart_OnMaxViewers_Failed {
            get {
                return ResourceManager.GetString("streetSmart_OnMaxViewers_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open image.
        /// </summary>
        internal static string StreetSmartCanNotOpenImage {
            get {
                return ResourceManager.GetString("StreetSmartCanNotOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not login the API.
        /// </summary>
        internal static string StreetSmartOnLoginFailed {
            get {
                return ResourceManager.GetString("StreetSmartOnLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemSearch16 {
            get {
                object obj = ResourceManager.GetObject("SystemSearch16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserTrash16 {
            get {
                object obj = ResourceManager.GetObject("UserTrash16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
