//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetSmartArcGISPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetSmartArcGISPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the terms of use..
        /// </summary>
        internal static string AgreementAcceptance {
            get {
                return ResourceManager.GetString("AgreementAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ConfigurationAddress {
            get {
                return ResourceManager.GetString("ConfigurationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass proxy server for local addresses.
        /// </summary>
        internal static string ConfigurationBypassProxy {
            get {
                return ResourceManager.GetString("ConfigurationBypassProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration url.
        /// </summary>
        internal static string ConfigurationConfigurationUrl {
            get {
                return ResourceManager.GetString("ConfigurationConfigurationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string ConfigurationDomain {
            get {
                return ResourceManager.GetString("ConfigurationDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string ConfigurationLocation {
            get {
                return ResourceManager.GetString("ConfigurationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ConfigurationPassword {
            get {
                return ResourceManager.GetString("ConfigurationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string ConfigurationPort {
            get {
                return ResourceManager.GetString("ConfigurationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy server.
        /// </summary>
        internal static string ConfigurationProxyServer {
            get {
                return ResourceManager.GetString("ConfigurationProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Smart location.
        /// </summary>
        internal static string ConfigurationStreetSmartLocation {
            get {
                return ResourceManager.GetString("ConfigurationStreetSmartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default.
        /// </summary>
        internal static string ConfigurationUseDefault {
            get {
                return ResourceManager.GetString("ConfigurationUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default credentials.
        /// </summary>
        internal static string ConfigurationUseDefaultCredentials {
            get {
                return ResourceManager.GetString("ConfigurationUseDefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a proxy server.
        /// </summary>
        internal static string ConfigurationUseProxyServer {
            get {
                return ResourceManager.GetString("ConfigurationUseProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string ConfigurationUsername {
            get {
                return ResourceManager.GetString("ConfigurationUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FocusMode16 {
            get {
                object obj = ResourceManager.GetObject("FocusMode16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error while opening the help document.
        /// </summary>
        internal static string HelpErrorOpenHelpDocument {
            get {
                return ResourceManager.GetString("HelpErrorOpenHelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no pdf viewer installed on your system.
        /// </summary>
        internal static string HelpNoPdfViewerInstalledOnYourSystem {
            get {
                return ResourceManager.GetString("HelpNoPdfViewerInstalledOnYourSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string ImageIdSearchDate {
            get {
                return ResourceManager.GetString("ImageIdSearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageId:.
        /// </summary>
        internal static string ImageIdSearchImageId {
            get {
                return ResourceManager.GetString("ImageIdSearchImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string ImageIdSearchLocation {
            get {
                return ResourceManager.GetString("ImageIdSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type:.
        /// </summary>
        internal static string ImageIdSearchProductType {
            get {
                return ResourceManager.GetString("ImageIdSearchProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string ImageIdSearchTime {
            get {
                return ResourceManager.GetString("ImageIdSearchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string LanguageGeneral {
            get {
                return ResourceManager.GetString("LanguageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageLanguage {
            get {
                return ResourceManager.GetString("LanguageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string LoginCheck {
            get {
                return ResourceManager.GetString("LoginCheck", resourceCulture);
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to Log out.
    /// </summary>
    internal static string LogoutCheck
    {
      get
      {
        return ResourceManager.GetString("LogoutCheck", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Check the username and password combination.
    /// </summary>
    internal static string LoginCheckText {
            get {
                return ResourceManager.GetString("LoginCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginLogin {
            get {
                return ResourceManager.GetString("LoginLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LoginStatus {
            get {
                return ResourceManager.GetString("LoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        internal static string LoginSuccessfully {
            get {
                return ResourceManager.GetString("LoginSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location is not supported in Scene.
        /// </summary>
        internal static string OpenLocationNotSupportedInScene {
            get {
                return ResourceManager.GetString("OpenLocationNotSupportedInScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth map.
        /// </summary>
        internal static string RecordingLayerDepthMap {
            get {
                return ResourceManager.GetString("RecordingLayerDepthMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail images.
        /// </summary>
        internal static string RecordingLayerDetailImages {
            get {
                return ResourceManager.GetString("RecordingLayerDetailImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Smart.
        /// </summary>
        internal static string RecordingLayerGroupName {
            get {
                return ResourceManager.GetString("RecordingLayerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoCyclorama Recording Points.
        /// </summary>
        internal static string RecordingLayerName {
            get {
                return ResourceManager.GetString("RecordingLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Authorization.
        /// </summary>
        internal static string RecordingLayerNoAuthorization {
            get {
                return ResourceManager.GetString("RecordingLayerNoAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate systems.
        /// </summary>
        internal static string SettingsCoordinateSystems {
            get {
                return ResourceManager.GetString("SettingsCoordinateSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclorama viewer.
        /// </summary>
        internal static string SettingsCycloramaViewer {
            get {
                return ResourceManager.GetString("SettingsCycloramaViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring not supported.
        /// </summary>
        internal static string SettingsMeasurementNotSupported {
            get {
                return ResourceManager.GetString("SettingsMeasurementNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring supported.
        /// </summary>
        internal static string SettingsMeasurementSupported {
            get {
                return ResourceManager.GetString("SettingsMeasurementSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay draw distance (meters).
        /// </summary>
        internal static string SettingsOverlayDrawDistance {
            get {
                return ResourceManager.GetString("SettingsOverlayDrawDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording layer.
        /// </summary>
        internal static string SettingsRecordingLayer {
            get {
                return ResourceManager.GetString("SettingsRecordingLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the overlay draw distance in the cyclorama..
        /// </summary>
        internal static string SettingsSetsOverlayDrawDistance {
            get {
                return ResourceManager.GetString("SettingsSetsOverlayDrawDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the image.
        /// </summary>
        internal static string StreetSmartCanNotOpenImage {
            get {
                return ResourceManager.GetString("StreetSmartCanNotOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not login to Street Smart.
        /// </summary>
        internal static string StreetSmartOnLoginFailed {
            get {
                return ResourceManager.GetString("StreetSmartOnLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemSearch16 {
            get {
                object obj = ResourceManager.GetObject("SystemSearch16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserTrash16 {
            get {
                object obj = ResourceManager.GetObject("UserTrash16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to Configuration url.
    /// </summary>
    internal static string ConfigurationVisibility
    {
      get
      {
        return ResourceManager.GetString("ConfigurationVisibility", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Configuration url.
    /// </summary>
    internal static string ConfigurationVisibilitySynced
    {
      get
      {
        return ResourceManager.GetString("ConfigurationVisibilitySynced", resourceCulture);
      }
    }
  }
}
